{
 "title": "API Metrics Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Prediction Errors Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "prediction_errors_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "95th Percentile Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(prediction_latency_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(prediction_errors_total[5m])",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(prediction_requests_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(prediction_requests_total[1m]) - rate(prediction_errors_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(prediction_errors_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}