channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=24.0
- pip:
  - mlflow==2.21.3
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - pandas==2.1.4
  - scikit-learn==1.6.1
  - scipy==1.15.2
name: mlflow-env
