groups:
- name: api_alerts
  rules:
  - alert: HighErrorRate
    expr: rate(prediction_errors_total[1m]) > 0
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: "High error rate detected"
      description: "Error rate is above 0 for the last minute"

  - alert: HighLatency
    expr: rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m]) > 0.1
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: "High latency detected"
      description: "Average request latency is above 100ms for the last minute"

  - alert: HighMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.8
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage"
      description: "Memory usage is above 80% for the last minute"

  - alert: HighRequestRate
    expr: rate(http_requests_total[1m]) > 10
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: "High request rate detected"
      description: "Request rate is above 10 requests per second for the last minute"

  - alert: HighCPUUsage
    expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 80
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage detected"
      description: "CPU usage is above 80% for the last minute"

  - alert: HighDiskUsage
    expr: (node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) / node_filesystem_size_bytes{mountpoint="/"} * 100 > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High disk usage detected"
      description: "Disk usage is above 85% for the last 5 minutes"

  - alert: ServiceDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Service is down"
      description: "Service {{ $labels.instance }} has been down for more than 1 minute" 